### PR TITLE
Fix bug in MockBaseStrategy.add_entry

### PR DESCRIPTION
**Pull request by whit537**
Over at https://github.com/whit537/cloud-custodian/pull/33#issuecomment-312659606 (more or less) I ran into this bug in `add_entry` where we use a text string as a basis for comparison with a byte (raw) string where we should be using the raw version instead.

### CODE REVIEW

**Comment by whit537** [comment]
Where is Travis? :thinking:

**Comment by whit537** [comment]
Hmmm ... well, here's the fix. ¯\\\_(ツ)\_/¯

**Comment by cannatag** [comment]
Please can you send this pull request to the dev branch instead of the master branch?

**Comment by whit537** [comment]
Base changed, @cannatag. 👍

**Comment by whit537** [comment]
Closed and reopened to hopefully trigger Travis ... no luck. 😞

**Comment by cannatag** [comment]
Sorry, Travis tests starts only when I push changes to the repository.

**Comment by cannatag** [comment]
I manually included the fix, cannot perform automatich merge. Thanks

**Pull request closed without merging**
