### PR TITLE
Fixes issue #800 - update requirements.txt to a later version of pyasn1

### PR DESCRIPTION
**Pull request by jannh**

### CODE REVIEW

**Comment by clokep** [comment]
This looks like the right fix to me! Without this you can run into a broken ldap3 install. Any chance of getting this merged / having a point release done? Thanks!

**Comment by dylancis** [comment]
Hi, would be great to have to merged. I still have the issue.

**Comment by cannatag** [comment]
Hi, It should be at least 0.3.1. Will modify the requirements.txt by myself. thanks!

**Comment by cannatag** [comment]
You're right, but I will include it in dev. Thanks!

**Pull request closed without merging**
