### PR TITLE
fix one exception missing (+Update changelog)

### PR DESCRIPTION
**Pull request by Augustin-FL**
I realized that I forgot to properly include `LDAPSignatureVerificationFailedError` in asynchronous strategy.

Sorry for that...

I also took the liberty to update the changelog

### CODE REVIEW

**Comment by cannatag** [comment]
Hi Augustin, I've already updated the code for the missing exception. Also I've changed a few of your code to be consistent with the variable naming convention (variables are lowercase with underscore while classes are CamelCase). My changes to your code are tagged with GC in inline comments. 

Can you check if it works as expected?

**Comment by Augustin-FL** [comment]
Hi,

I've tested LDAP signing on various AD domains with the default strategy (SYNC), no issue so far. I'll try the other strategies this week to give you a complete feedback

**Comment by Augustin-FL** [comment]
Hi,

I've tested all other strategies...everything's good.
 
Thanks for the rework !

**Comment by Augustin-FL** [comment]
@cannatag One question : when do you plan to release the version 2.8.2? (or 2.9.0? ). Do you have any schedule planned? 

I'm asking cause I can't wait to use my PR in production environment 😄

**Comment by cannatag** [comment]
I’m waiting for some testing on Windows AD. Hope to release 2.9 in a week or two.

Bye,
Giovanni

**Pull request closed without merging**
