### PR TITLE
add a cache for referral connections

### PR DESCRIPTION
**Pull request by TWAC**
When I make a lot of searches that hits referrals, connection time quickly adds up.
This PR adds a cache speeding things up significantly.

### CODE REVIEW

**Comment by cannatag** [comment]
Thanks l will study your code in the weekend.

**Comment by TWAC** [comment]
I discovered that referrals_followed was incorrect with the cache, so I pushed another commit.

**Comment by cannatag** [comment]
I'm about to release version 2 of ldap3. Can't automatically merge this because I modified the connection.py source file. Will try to include your code manually.

Thanks,
Giovanni

**Comment by TWAC** [comment]
I rebased it, should be mergeable now.

**Comment by cannatag** [comment]
Just released version 2.0.7. Will include your par in next release. Thanks

**Comment by cannatag** [comment]
Released in version 2.0.8.

Thanks,
Giovanni

**Pull request merged**
