### PR TITLE
Fix pickling of entry and attribute

### PR DESCRIPTION
**Pull request by cfelder**
Entry and Attributes are not pickable because they all have indirect references to the Connection object holding a `threading.RLock`. With this patch the pickled representation of the objects is reduced by its cursors holding a reference to the Connection.

This merge request also fixes a violation of ``__getattr__`` and ``__setattr`` interfaces

This merge request is motivated by following issue: cfelder/ldap3-orm#5

### CODE REVIEW

**Comment by cannatag** [comment]
Please could you send the PR to the dev branch?

Thanks,
Giovanni

**Comment by cfelder** [comment]
Hello Giovanni,

sorry for the delayed response. I am just back from vacation.

> Please could you send the PR to the dev branch?

I thought this is more considered as a bugfix on current master but if you prefer to have this on dev I will change my PR.

Best
Christian

**Comment by cfelder** [comment]
@cannatag 

* first of all I wish you the very best for the new year.

* can we merge this or is there any need to change something? please let me know.

Best
Christian

**Comment by cannatag** [comment]
Hi @cfelder, happy new year to you too!
I will work on the ldap3 project in the weekend. Hope to have an update soon.

Bye,
Giovanni

**Comment by cannatag** [comment]
Hi, could you check the code in dev? 

Thanks.
Giovanni

**Comment by cfelder** [comment]
I can confirm that dev **c6bd5650** works fine.

Best
Christian

**Pull request merged**
