### PR TITLE
fix paged search while using the Reader.search_paged() method.

### PR DESCRIPTION
**Pull request by wazboy**
I was not able to get paged searches working with the Reader abstraction.  I changed the behavior of the method.

* The cookie was not saved in Reader._execute_query().
  *  This results in only getting the first page of query results on each invocation.
* The Reader.search_paged() method would only yield once.
* The Reader.search_paged() method would yield a list of entries, not each entry found.

This pull request modifes the Reader._execute_query() method to save the cookie.  It also changes the ergonomics of Reader.search_paged() so it can be used as follows:

```python
    person_reader = Reader(c, person_def, '', 'ou=Users,dc=lazarus,dc=com')

    for person in person_reader.search_paged(5):
        print(person.givenName, person.sn)
```

### CODE REVIEW

**Comment by cannatag** [comment]
Thanks, I will test your code and include it in the next release of ldap3-

Bye,
Giovanni

**Comment by cannatag** [comment]
Hi wazboy,
I've removed the paged_search logic from the reader object and have integrated the newer connection.extend.paged_search() method in the reader itself. I prefer this approach because I have the paged search logic in only one place. With the parameter generator=True|False You can choose to have the reader to behave as a generator (ldap searches are performed while you consume the entries) or accumulator (all paged search are performed before you read the first entry). I've committed the changes in dev. Can you test if this is working for you?

Thanks, 
Bye,

**Comment by wazboy** [comment]
Hi cannatag,

I've tested the changes in the dev branch.  This has the same semantica behavior as the changes in this pull request.  As such it works perfectly.  I agree that leveraging the existing paged_search from the extended module promotes code reuse.  You changes are superior to this pull request.

Regards

**Comment by cannatag** [comment]
Thanks for testing. I will release it in 0.9.8.2

Bye,
Giovanni

**Pull request closed without merging**
